[package]
name = "pca9685"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.17.1"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["time", "full"] }
